### ISSUE TITLE
几个问题和建议

### ISSUE THREAD

**Issue by hkspirt** [vckai/novel#1]
SnatchTaskManager.tasks   多个goroutine并发访问，有崩溃的风险
detail.tpl缺少echo.js封面没加载
proxy建议剔出来，和业务本身没什么关系，util里面的几个函数直接使用不要传参了(我改成自己的了github.com/hkspirt/proxy)

抓取章节内容失败后好像只做了status标记，没有重试机制？
考虑加一层redis？书籍列表式+章节列表+部分章节缓存放redis里，要抗的住些？

**Comment by hkspirt** [comment]
go func() 建议封装一下使用参考：github.com/hkspirt/proxy/blob/master/util/util.go
另：代码不错。。。已copy。。。求后续。。。

**Comment by vckai** [comment]
感谢你的反馈:)

1. SnatchTaskManager.tasks 应该我就启用了10个goroutine吧，是具体哪里可能会导致崩溃呢。
2. detail.tpl的echo.js 我这边测试是OK的。
3. proxy之前是有抽离一个单独的proxy，但是发现后来采集的代理IP可用度不高，就放弃了。不过代码一直没有去除掉，后续我会考虑把这块统一处理下。
4. 抓取失败的确实是还没有做2次处理（主要懒），有这个计划了，因为最近发现抓取失败的概率挺高的。
5. redis的暂时还没有这个计划。

**Comment by hkspirt** [comment]
1.map不是线程安全的，只要有多协程读写就得加锁(读多写少换sync.Map)，不然就可能随机崩
2.我这边pull下来detail.tpl中没有echo.js...

**Comment by vckai** [comment]
1. map的操作都是有加锁的，至于task本身运行是只允许一个协程在运行的。
2. echo.js 的引用是在`home/default/common/footer.tpl`这个文件中，是echo.js文件不存在，还是没有引用呢？

**Comment by vckai** [comment]
已增加章节失败重试机制
