### ISSUE TITLE
线上环境

### ISSUE THREAD

**Issue by kunguang** [vckai/novel#11]
线上环境，直接把runmode改成pro，httpaddr改成服务器地址。一直报 ListenAndServe:  listen tcp 39.97.99.111:8080: bind: cannot assign requested address
![image](https://user-images.githubusercontent.com/3446934/59149932-82ea8300-8a4e-11e9-9d3b-80e65db956d5.png)

**Comment by vckai** [comment]
你ifconfig看下是不是这个IP没有绑定在你网卡上，阿里云/腾讯云服务器的外网IP都是经过地址转发的，所以从服务器本身无法直接绑定外网IP
