### ISSUE TITLE
遇到问题...分类无效

### ISSUE THREAD

**Issue by Lumysia** [vckai/novel#15]
遇到几个问题...实在不知道怎么回事...求教
1. UI
 > 小说管理->分类管理中，操作下的编辑，本来应该是"是否菜单"变成了"是否首页"

2. 程序
 > 前提：我把两个预设的数据库导入在一个数据库里，不知道会不会冲突
 > 正确运行爬虫后，分类已绑定，但PC版全部作品(site/home/cate)中无任何作品，分类中无作品，搜索没有任何作品，WAP版中所有分类作品全部一样(分类无效)，只有搜索正常
 > 测试添加固定分类小说之后，分类查看依然无效

3. 建议
 > 希望大佬添加普通用户账户系统啦...就像是投稿这样的

**Comment by vckai** [comment]
2. 导入同一个数据库不会影响。
能否截图看下，首页的查看截图，后台的小说列表截图，找个小说编辑进行截图。另外查看首页时的日记截图看下。

3. 暂时不会考虑添加普通用户账号系统

**Comment by Lumysia** [comment]
首页：
![](https://i.loli.net/2019/08/28/FIzpRjGPceZxK1W.png)
后台：
![](https://i.loli.net/2019/08/28/zsiQOkfI1YqFSxK.png)
编辑：
![](https://i.loli.net/2019/08/28/IwzVnb9LcjuHvKW.png)
查看首页时的服务器日志：
![](https://i.loli.net/2019/08/28/MZ2lDqUtIOsnPb9.png)

是分类里面什么都没有啊...
![](https://i.loli.net/2019/08/28/vhgxB5JQXI9fdzj.png)

**Comment by vckai** [comment]
多谢反馈，已修复，请拉取下最新代码
