### ISSUE TITLE
封面无法显示和一些其他问题

### ISSUE THREAD

**Issue by Lumysia** [vckai/novel#16]
* UI
	1. 所有小说封面全部是默认封面，点开之后的目录页封面图正常(按理来说采集正常啊…)
	2. 已展开状况下作品简介如果太长最后会被截断
* 程序
	1. **采集规则-是否用于强制更新图片**选项无法启用
	2. PC版**分类页面**和**搜索结果**页面中的小说字数全部都是0字
* 建议
	1. 建议PC版目录能倒序排列
	2. 建议书籍目录页的category-lst类元素显示作品所属分类
	3. 建议能够展示爬虫的进度或者目前处理情况...不然还得去查看程序运行日志…
	4. 手机版搜索非常慢，也许能调优…(从采集站查找太浪费时间？禁用采集站又不能自动每日更新…希望能有个选项控制…)
	5. Web框架的404页面和小说网站页面配色实在不一致…

大佬有时间看看呗...

**Comment by vckai** [comment]
* UI
	1. BUG
* 程序
	2. BUG
* 建议
	4. 这个设置app.conf 的runmode为prod则会屏蔽


多谢反馈，这几个BUG都是由于之前我进行代码优化时导致的，我会抽空处理掉。
但是反馈的建议可能我近期暂时没这么精力进行处理，也欢迎你提交PR

**Comment by Lumysia** [comment]
感谢大佬解惑
目前我正在学习Golang...如果有能力处理这些问题我会来提PR的.

**Comment by vckai** [comment]
欢迎入坑Golang，期待你的PR
