### ISSUE TITLE
关于打包

### ISSUE THREAD

**Issue by bajins** [vckai/novel#17]
### 可参考
* [https://www.bajins.com/Go/Go打包.html#打包脚本](https://www.bajins.com/Go/Go%E6%89%93%E5%8C%85.html#%E6%89%93%E5%8C%85%E8%84%9A%E6%9C%AC)

* [https://github.com/fatedier/frp/blob/master/package.sh](https://github.com/fatedier/frp/blob/master/package.sh)

**Comment by vckai** [comment]
本身编译比较简单，也没太多可配置以及第三方依赖。
暂时不考虑添加打包脚本

**Comment by bajins** [comment]
> 本身编译比较简单，也没太多可配置以及第三方依赖。
> 暂时不考虑添加打包脚本

建议打包，之前有小白问我怎么弄

**Comment by bajins** [comment]
小白不会解决编译之前的依赖安装

**Comment by vckai** [comment]
这个没什么依赖安装呀，基本第三方包都存有在vendor里。如果使用go mod的话，go mod就会自动下载第三方包。
