### ISSUE TITLE
大佬您好，对您的程序非常感兴趣，能否给下QQ号？ 

### ISSUE THREAD

**Issue by xufeifly** [vckai/novel#19]
有点问题咨询下您，谢谢

**Comment by vckai** [comment]
有什么问题可以直接发我邮箱：admin@vckai.com ，一般都能及时回复的：）

**Comment by xufeifly** [comment]
谢谢！非常感谢你的源码，我业余在学golang。。关于小说源码就是采集系统的怎么写？有没有规则说明啊？我看的有点晕》》另外还有会员的功能或者其他功能在开发吗？

**Comment by vckai** [comment]
Hi

1. 采集系统是问的采集规则怎么写吗？

目前采集一本小说的一般分为三个页面（有些站点小说详细信息和章节列表是同一个页面）：
* 小说详细信息页。
* 小说章节列表页。
* 小说章节内容页。

采集规则主要通过css选择器进行相应的数据（比如小说标题，小说作者等）采集，类似jQuery选择器。
关于这个采集规则怎么写，具体可以查看css选择器文档以及参考现有的采集规则，通过“模拟测试获取页面元素”工具来进行测试获取到相应的小说内容。

采集规则里有两个正则表达式的规则，这两个主要是防止采集到错误的页面，所以通过URL正式判断确认是否我们想要的页面。
* 小说简介页URL规则
* 允许爬虫页面URL规则

2. 目前的话暂时没有其他功能在开发中

你发给我的邮箱无法回复，所以在这里回复你了。
