### ISSUE TITLE
网页显示Not Found

### ISSUE THREAD

**Issue by IamQiuTian** [vckai/novel#2]
输出如下：
`[ORM]2019/03/21 21:15:26 register db Ping `chapter`, Error 1049: Unknown database 'gochapter'
[ORM]2019/03/21 21:15:26  -[Queries/default] - [  OK /    db.Query /     0.8ms] - [SELECT T0.`id`, T0.`name`, T0.`status` FROM `nov_novel` T0 WHERE T0.`deleted_at` = ? AND T0.`status` = ? ORDER BY T0.`id` DESC LIMIT 10000000] - `0`, `1`
2019/03/21 21:15:26 [I] [log.go:38] 初始化小说更新任务: 0 本 
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: home/default/book/index.tpl template: home/default/book/index.tpl:50: function "num_format" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: home/default/home/cate.tpl template: home/default/home/cate.tpl:94: function "substr_no_html" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: home/default/home/index.tpl template: home/default/home/index.tpl:16: function "css" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: home/default/home/search.tpl template: home/default/home/search.tpl:46: function "substr_no_html" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: m/default/book/index.tpl template: m/default/book/index.tpl:20: function "datetime" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: admin/chapter/index.tpl template: admin/chapter/index.tpl:51: function "datetime" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: admin/admin_log/index.tpl template: admin/admin_log/index.tpl:56: function "datetime" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: admin/novel/find_snatch.tpl template: admin/novel/find_snatch.tpl:21: function "substr_no_html" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: admin/novel/index.tpl template: admin/novel/index.tpl:65: function "datetime" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: admin/novel/links.tpl template: admin/novel/links.tpl:18: function "datetime" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: m/default/snatch/index.tpl template: m/default/snatch/index.tpl:20: function "datetime" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: admin/banner/index.tpl template: admin/banner/index.tpl:40: function "datetime" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: admin/feedback/index.tpl template: admin/feedback/index.tpl:35: function "datetime" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: admin/home/index.tpl template: admin/home/index.tpl:7: function "datetime" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: home/default/common/page.tpl template: home/default/common/page.tpl:6: function "i18n" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: m/default/home/index.tpl template: m/default/home/index.tpl:94: function "substr_no_html" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: admin/admin/add.tpl template: admin/admin/add.tpl:31: function "itoa" not defined
2019/03/21 21:15:26 [D] [hooks.go:75] parse template err: admin/admin/index.tpl template: admin/admin/index.tpl:38: function "itoa" not defined
2019/03/21 21:15:26 [I] [asm_amd64.s:2361] http server Running on http://:8089`

**Comment by vckai** [comment]
请给出相关运行环境以及软件版本。另错误提示格式太乱了，麻烦整理下。:)
看这个错误提示是beego的模板函数没有注册成功。

调用注册的流程如下，看下是否有正常调用beego的模板函数注册。
```
1. main.go
import (
    "github.com/astaxie/beego"

    _ "github.com/vckai/novel/app"  // 初始化
)

2. app/init.go
// 注册模板函数
utils.RegisterFuncMap()


3. app/utils/template.go

 func RegisterFuncMap() {
     // 注册模板函数
     beego.AddFuncMap("datetime", GetDateFormat)
     beego.AddFuncMap("itoa", IntToString)
     beego.AddFuncMap("substr_no_html", SubstrNoHtml)
     beego.AddFuncMap("add", Add)
     beego.AddFuncMap("css", Css)
     beego.AddFuncMap("num_format", NumFormat)
     beego.AddFuncMap("urlfor", URLFor)
 }
```

**Comment by IamQiuTian** [comment]
OS : Ubuntu 16.04.3
GO:  go1.10
