### ISSUE TITLE
采集小说

### ISSUE THREAD

**Issue by lyuly** [vckai/novel#20]
默认采集点击后，显示成功，但是实际没有采集到小说，log也没有报错。请问怎么导入小说规则呢，希望能给个示例

**Comment by vckai** [comment]
`采集规则`在后台`小说管理->采集规则`可以看到，导入规则的示例在 `./data/rule` 目录下有，直接复制规则文件的内容通过后台管理可以导入。

默认采集是指哪里？目前有两种方式采集小说。
* 手动采集，后台“小说管理->小说列表” 输入小说名称会自动从现有的采集规则站搜索小说，点采集即可采集单个小说。
* 自动采集，后台“小说管理->小说列表”有一个运行爬虫的按钮，点击可以选择现有的规则站进行整站采集，这个采集是在后台运行的，采集速度具体看目标站的速度，可能需要等一会才会有数据。

可以先通过`手动采集`和`采集规则`的测试功能，先测试看下采集站的规则是否还正常。因为由于站点规则变化会导致`采集规则`失效。

**Comment by lyuly** [comment]
蟹蟹。OK了
