### ISSUE TITLE
我帮你修复了一下移动端的brook\detail.tpl

### ISSUE THREAD

**Issue by pingProMax** [vckai/novel#21]
关灯开灯 大字、中字、小字记忆功能

<script type="text/javascript">

$(function(){
	var d= localStorage.getItem("d"); //获取灯
	if(d != null){
		if(d!='off'){//开启
			light("on") 
		}else{//关
			light("off") 
		}
	}
	
	var book_font_sizi = localStorage.getItem("book_font_sizi"); //获取书本字体大小
	if(book_font_sizi != null){
		font(book_font_sizi)
	}
})

function light(off) {
	

    if(off != 'off') {
		localStorage.setItem("d", "on"); //开灯
		$("body").css("background-color","rgb(249, 249, 249)").css("color","rgb(0, 0, 0)")

    }else{
		localStorage.setItem("d", "off"); //关灯
		$("body").css("background-color","rgb(34, 34, 34)").css("color","rgb(153, 153, 153)")
	}

}

function font(size) {
    var big = '26px';
    var middle = '22px';
    var small = '16px';

    switch(size) {
        case 'big':
            document.getElementsByTagName('article')[0].style.fontSize = big;
			localStorage.setItem("book_font_sizi", "big"); 
            break;
        case 'middle':
            document.getElementsByTagName('article')[0].style.fontSize = middle;
			localStorage.setItem("book_font_sizi", "middle"); 
            break;
        case 'small':
            document.getElementsByTagName('article')[0].style.fontSize = small;
			localStorage.setItem("book_font_sizi", "small"); 
            break;
    }

    document.cookie = "font="+size+";path=/";
}
</script>

**Comment by vckai** [comment]
能否提交个格式化的JavaScript代码，或者fork项目提交个pr过来？
感谢~

**Comment by pingProMax** [comment]
> 能否提交个格式化的JavaScript代码，或者fork项目提交个pr过来？
> 感谢〜

已经提交:)

**Comment by vckai** [comment]
已合并，感谢：）
