### ISSUE TITLE
代理配置

### ISSUE THREAD

**Issue by pingProMax** [vckai/novel#25]
代理配置->代理URL
我该怎么设置？？

**Comment by pingProMax** [comment]
我想使用代理去采集 因为服务器的ip似乎被屏蔽

**Comment by pingProMax** [comment]
my dear DaLao, please Bang Bang Wo!

**Comment by vckai** [comment]
如果使用的是IP模式的话，配置URL为：`http://user:passwd@ip:port `，
示例：`http://user:passwd@ip4.hahado.cn:35044`

还有一个自动模式，是通过第三方平台接口返回IP列表，爬虫会在这个IP列表中自动选取IP进行代理。这个第三方平台接口可以使用[proxypool](https://github.com/henson/proxypool)，  [IPProxyPool](https://github.com/qiyeboy/IPProxyPool) 这些免费的IP代理池，不过IP一般可用性不高。

**Comment by pingProMax** [comment]
第三方平台接口返回IP列表, 返回的json 格式是咋样的？
我看这两项目的案例中有这样的：
[["122.226.189.55", 138, 10], ["183.61.236.54", 3128, 10], ["61.132.241.109", 808, 10], ["183.61.236.53", 3128, 10], ["122.227.246.102", 808, 10]]

和这样的：
{
    ip:"192.168.1.1:6666",
    type:"http"
}

**Comment by pingProMax** [comment]
我好像知道了，似乎需要这样的格式：
{
  "data": [
    {
      "ip": "127.0.0.1",
      "port": "1080"
    },
    {
      "ip": "127.0.0.1",
      "port": "1080"
    }
  ]
}

**Comment by 344085057** [comment]
PICTURE:/home/ping/.config/tencent-qq//AppData/file//sendpix0.jpg

**Comment by pingProMax** [comment]
我在测试过程中项目直接崩溃了！

panic: runtime error: slice bounds out of range [2:1]

goroutine 23 [running]:
github.com/vckai/novel/app/services.(*Proxy).Del(0xc00018a4c0, 0xc0001f2400, 0xe, 0x0, 0xc000416ae0)
        /home/ping/go/src/github.com/vckai/novel/app/services/proxy.go:153 +0x253
github.com/vckai/novel/app/services.(*Proxy).check(0xc00018a4c0)
        /home/ping/go/src/github.com/vckai/novel/app/services/proxy.go:201 +0x2e4
github.com/vckai/novel/app/services.(*Proxy).Init.func2(0xc00018a4c0)
        /home/ping/go/src/github.com/vckai/novel/app/services/proxy.go:76 +0x91
created by github.com/vckai/novel/app/services.(*Proxy).Init
        /home/ping/go/src/github.com/vckai/novel/app/services/proxy.go:70 +0x61

**Comment by 344085057** [comment]
这个代理是需要http代理还是socks5 
因为我刚刚测试 代理服务器返回的信息是：Invalid Version

**Comment by pingProMax** [comment]
我知道了 我全知道了  ：）

**Comment by pingProMax** [comment]
使用代理采集 程序一直崩溃！！

**Comment by vckai** [comment]
采集使用代理崩溃的问题我另外创建了一个issue来跟进，有问题在那个issue反馈。：）
