### ISSUE TITLE
写入内容失败

### ISSUE THREAD

**Issue by ciweiin** [vckai/novel#3]
2019/03/22 02:57:23 [W] [log.go:28] [小说更新任务] ID: 2  小说: 神圣罗马帝国  provider: 23txt  批量写入章节内容失败 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' status=?, created_at=?, updated_at=?' at line 1

**Comment by vckai** [comment]
谢谢反馈，已修复
