### ISSUE TITLE
IO过高

### ISSUE THREAD

**Issue by lyuly** [vckai/novel#30]
我在后台采集配置里把每天自动采集新小说，采集排行榜，自动更新章节都打开了，更新间隔为2，停更天数为10。结果，一个多月下来，主机商告知我IO频繁，大概消耗了144TB流量😂。请问该怎么设置采集配置？更新间隔是以天数算还是小时呀

**Comment by vckai** [comment]
更新时间是以秒为单位的，数据库也在同一台服务器上吗？
这个流量消耗这么大？老实说我也没具体测试过😂

**Comment by lyuly** [comment]
数据库和网站在同一台服务器上，看来得把更新间隔设置稍微大点，不至于频繁读写磁盘

**Comment by vckai** [comment]
小说比较多的情况下是要把间隔时间设置大一些，另外如果有代理ip的话可以开启多一些协程去跑

**Comment by lyuly** [comment]
好的，蟹蟹了
