### ISSUE TITLE
收藏功能和小说状态

### ISSUE THREAD

**Issue by garylab** [vckai/novel#32]
你好，

请问收藏功能是否可以不受浏览器限制，写入cookie之类的呢？

另外，小说更新时没有【状态】采集，前台都是“连载中”，这个后面是否考虑增加呢？

**Comment by vckai** [comment]
1. 收藏功能目前只是一个简单的浏览器书签记录，放入cookie也是要受浏览器限制呀？你想说的是收藏小说吗？这个有规划，将阅读记录和收藏记录存入浏览器缓存中。
2. 小说更新是会更新状态的，不过不是根据目标站的状态来更新。而是判断小说章节标题出现【结局、完本、本书完】之类的就会自动将状态变更为【完本】，另外十天如果小说没有更新的话也会被变更为【太监】（目前这个可能太一刀切了）。

**Comment by garylab** [comment]
> 1. 收藏功能目前只是一个简单的浏览器书签记录，放入cookie也是要受浏览器限制呀？你想说的是收藏小说吗？这个有规划，将阅读记录和收藏记录存入浏览器缓存中。
> 2. 小说更新是会更新状态的，不过不是根据目标站的状态来更新。而是判断小说章节标题出现【结局、完本、本书完】之类的就会自动将状态变更为【完本】，另外十天如果小说没有更新的话也会被变更为【太监】（目前这个可能太一刀切了）。

1. 嗯，我的收藏小说意思和你规划的一样的，收起来方便下次重新阅读方便。现在大部分都会开的cookie，或者storage，大部分浏览器应该支持，小部分可以忽略。
2. 这个可以慢慢优化，都是不着急。

另外，这个项目很不错，点个赞！！！建议readme加个赞助二维码，很多有心的人应该都想支持，也有个便捷的渠道

**Comment by vckai** [comment]
这个项目只是我自己的一个业余兴趣项目，所以暂时就不考虑放赞助二维码了：）
