### ISSUE TITLE
章节列表页面有分页现在是否有处理方案呢？

### ISSUE THREAD

**Issue by garylab** [vckai/novel#33]
你好，

有的网站的简介页面也是章节链接的列表页，不过分了很多页，这个现在是否有处理方案呢，谢谢！

**Comment by vckai** [comment]
是指PC站的章节没有做分页处理吗？

**Comment by garylab** [comment]
额，我没表达清楚，被采集网站的章节列表如果做了分页，这个有木有办法采集呢？我现在只能采集到第一页的那些章节。比如某部小说有100章，被采集网站做了分页，每页显示50章，我手动点测试的话，只能采集前50章，后50章采集不到。

**Comment by vckai** [comment]
哦，你采集的是手机站的吧？之前主要都是针对PC站。所以没考虑这个问题。
可以在章节规则增加一个分页的css选择器，通过选择器判断是否存在下一页，等我稍后弄一下吧。

**Comment by vckai** [comment]
增加了目标站章节分页的处理，不过不建议采集章节有分页的站点，采集效率太低。

**Comment by garylab** [comment]
好的，我试试
