### ISSUE TITLE
采集规则里没有看到替换功能。

### ISSUE THREAD

**Issue by ytidc** [vckai/novel#38]
可以增加替换功能吗？或者说一下在哪个文件里增加

**Comment by vckai** [comment]
替换功能？具体是指替换什么呢？

**Comment by ytidc** [comment]
if strings.Contains(v, " | ") {
			aR := strings.Split(v, " | ")
			v = aR[0]
			replaced = aR[1]
		}
		re, _ := regexp.Compile("(?U)" + v)
		kw = re.ReplaceAllString(kw, replaced)

这段代码是不是 加了|后,就可以把 |前面的字符替换为后面的

**Comment by vckai** [comment]
是想替换掉采集到的小说标题，作者，分类，内容的部分内容吗？在过滤规则里通过添加" | "分割符（注意分割前后有空格），可以将前面的替换为后面的，默认替换为空。

**Comment by ytidc** [comment]
好的 谢谢了,这个项目还会更新吗?

**Comment by vckai** [comment]
还会更新，不过近期工作上比较忙，可能更新没那么及时

**Comment by ytidc** [comment]
感谢.

**Comment by ytidc** [comment]
http://www.7yun.org/这个网站他的章节顺序,源码里是乱的,有办法排序吗,他自己是用的id排序
