### ISSUE TITLE
请问编译不了怎么解决呢？

### ISSUE THREAD

**Issue by bajins** [vckai/novel#4]
```
main.go:20:2: cannot find package "github.com/vckai/novel/app" in any of:
	/usr/lib/golang/src/github.com/vckai/novel/app (from $GOROOT)
	/root/go/src/github.com/vckai/novel/app (from $GOPATH)
```

**Comment by vckai** [comment]
你设置的GOPATH路径为：/root/go/。
代码是不是没有下载到/root/go/src？

**Comment by vckai** [comment]
执行：go get github.com/vckai/novel，然后进入：cd $GOPATH/src/github.com/vckai/novel，编译即可。

**Comment by bajins** [comment]
> 你设置的GOPATH路径为：/root/go/。
> 代码是不是没有下载到/root/go/src？

我是通过yum安装的go

**Comment by bajins** [comment]
> 执行：go get github.com/vckai/novel，然后进入：cd $GOPATH/src/github.com/vckai/novel，编译即可。

非常感谢
