### ISSUE TITLE
小说名字相同但是作者不同

### ISSUE THREAD

**Issue by ytidc** [vckai/novel#40]
小说名字相同但是作者不同，是不是就不能入库。

**Comment by vckai** [comment]
是的，之前判断比较简单，直接通过小说名来进行判断的。不过这个也可以调整为小说名+作者来做限制，`app/services/snatch.go` 的  `NovelService.GetByName` 可以增加一个作者参数进行判断

**Comment by ytidc** [comment]
我翻到这两个文件了,但是不懂你的写法,怕搞出BUG,不敢动.

**Comment by vckai** [comment]
挺简单的，可以尝试进行修改下

**Comment by ytidc** [comment]
还有个BUG, 前端手机页面有时会css加载失败,会变成纯文字页面,没有样式,刷新几次又会恢复.

**Comment by vckai** [comment]
我这里没有出现过，可以使用chrome的开发者工具查看下css文件加载情况，是不是网络问题导致的加载失败。

**Comment by ytidc** [comment]
应该不是 我换了网络坏境,也试过加CDN,都会出现

**Comment by vckai** [comment]
可以通过开发者工具查看下css加载情况，看下具体什么错误

**Comment by ytidc** [comment]
好的
