### ISSUE TITLE
建议把采集器和网站分开。

### ISSUE THREAD

**Issue by ytidc** [vckai/novel#41]
现在这样采集的时候log输出太乱没办法看，采集器一旦运行就不能停止。。

**Comment by vckai** [comment]
采集器可以通过后台配置进行关闭

**Comment by ytidc** [comment]
没找到关闭的位置，还有想问个问题，比如一本小说源站没有更新了，我用另一个站的规则，能不能继续采集？

**Comment by vckai** [comment]
在`系统设置`->`网站配置`->`采集设置`里可以配置。

可以继续采集的
