### ISSUE TITLE
你好，这个采集规则不太懂

### ISSUE THREAD

**Issue by vckai** [vckai/novel#42]
你好，这个采集规则不太懂，比如我要采集webnovel.com上面的小说，怎么设置采集规则

_Originally posted by @fjgui in https://github.com/vckai/novel/issues/29#issuecomment-630273165_

**Comment by vckai** [comment]
#19

**Comment by vckai** [comment]
@fjgui 可以参考 #19

**Comment by ytidc** [comment]
就是goquery百度搜一下很多教程

**Comment by ytidc** [comment]
这个采集器只能采集笔趣阁那样的简单页面，复杂页面需要自己写爬虫直接入库。
