### ISSUE TITLE
关于采集内容的问题

### ISSUE THREAD

**Issue by cookie-session** [vckai/novel#43]
我这边无法 采集到 文章的内容  有个别小说可以

**Comment by vckai** [comment]
可以将采集规则贴出来

**Comment by cookie-session** [comment]
规则我采用的是 自带的 bbiquge.txt 这个采集规则

**Comment by cookie-session** [comment]
Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 502 Bad Gateway\r\nContent-Type: text/html\r\nConnection: close\r\nContent-Length: 288\r\nDate: Thu, 28 May 2020 13:08:25 GMT\r\nX-Via: 1.1 R84S-14 (random:668195 cache/3.8.1)\r\n\r\n"; err=<nil>
