### ISSUE TITLE
请问后续是否会增加加入添加采集规则的功能呢？

### ISSUE THREAD

**Issue by bajins** [vckai/novel#5]
### 以下是ygbook的采集规则添加
![image](https://user-images.githubusercontent.com/30252550/55072678-adbb7100-50c6-11e9-9b10-307a9d85d72c.png)
![image](https://user-images.githubusercontent.com/30252550/55072747-de030f80-50c6-11e9-81d5-7b38e1cc3313.png)

**Comment by vckai** [comment]
这个可以考虑，有没有相关的演示站点可以看下？

**Comment by bajins** [comment]
> 这个可以考虑，有没有相关的演示站点可以看下？

把我的给你看看？但是是我的线上环境，私聊？

**Comment by vckai** [comment]
好的，麻烦加下我QQ：348024384
