### ISSUE TITLE
爬虫状态以及统计的功能扩展！

### ISSUE THREAD

**Issue by skydiy** [vckai/novel#59]
目前爬虫只有在运行后的日志，但后台无法看到一些当前状态和统计信息
比如：今天爬完的书籍数量、爬完的完整章节的书籍数量等
还有就是当前爬的什么书 章节爬取进度等！
不知道作者目前是不是会考虑这些！

**Comment by vckai** [comment]
后续会将这个加入进来，方便后台查看爬虫以及采集日记

**Comment by skydiy** [comment]
OK 期待项目越来越完善 也希望项目能有更多创新功能的探索！
