### ISSUE TITLE
编译出来学习一下，但是出现了问题，有没有大佬帮帮忙？

### ISSUE THREAD

**Issue by 1525273823** [vckai/novel#68]
![image](https://user-images.githubusercontent.com/36191807/181741022-5707f3b7-c66e-499c-acbd-a7ca0ce84c0e.png)
其他流程应该是没有问题

**Comment by vckai** [comment]
看下 `nov_config` 表有一个 `Theme` 配置是否为空？确认下 `nov_config` 表配置数据是否已导入

**Comment by 1525273823** [comment]
> 看下 `nov_config` 表有一个 `Theme` 配置是否为空？确认下 `nov_config` 表配置数据是否已导入

好的，已经弄好了，谢谢
